### PR TITLE
some refactoring.

### PR DESCRIPTION
**Pull request by dsm**
Hi, this PR do some refactoring.

### CODE REVIEW

**Comment by dsm** [comment]
@ra3xdh I'm beginning to refactoring some q3PtrList but it take some time and tomorrow I'll be on a 5-day holiday.I don't used sharedObjectList from qucs.

**Comment by ra3xdh** [comment]
> I'm beginning to refactoring some q3PtrList but it take some time and tomorrow I'll be on a 5-day holiday

That is good news. I can assign #748 to you. I am planning to prepare v24.3.0 release within next two weeks. So, we can schedule this refactoring for the v24.4.0.

**Comment by ra3xdh** [comment]
@dsm, Please look at #845. This PR removes Q3PtrList from `Node` class. Please check for possible conflicts.

**Comment by dsm** [comment]
@ra3xdh Hi, Maybe I'll close this PR, I need to refactor the codes step by step for my limited time. I might have to look at it from a different perspective.

**Pull request closed without merging**
