### PR TITLE
Add AppImage to continous release

### PR DESCRIPTION
**Pull request by ra3xdh**
This is follow-up of #799. It deploys AppImage when making continuous release.

### CODE REVIEW

**Comment by dsm** [comment]
build-linux-appimage-qt6 should added release section

```yaml
  create-release:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs:
     - build-linux-appimage-qt6
     #- build-linux
     - build-mac-intel
     - build-mac-arm
     - build-windows
```

**Comment by ra3xdh** [comment]
I have just updated the `needs` section in `deploy.yml`.

**Comment by dsm** [comment]
actions/checkout@v3 and actions/upload-artifact@v2 should be updated to v4 other section uses v4 and upload artifact name should be this. 
```yaml
name: Qucs-S-x86_64-Linux 
```

**Comment by dsm** [comment]
this line is mistakenly changed on my pr 'share' folder to 're'. can you make this change for me.

correct: QUCS_MACOS_RESOURCES: ./build/qucs/qucs-s.app/Contents/MacOS/share/qucs-s/

**Comment by ra3xdh** [comment]
@dsm, I have added a fix by the latest commit.

**Comment by dsm** [comment]
@ra3xdh thanks.

**Comment by ra3xdh** [comment]
Merged.

**Pull request merged**
