### PR TITLE
S-parameter viewer

### PR DESCRIPTION
**Pull request by andresmmera**
I have added an S-parameter viewer to the Qucs-S toolset. The idea originated in #733 with the approval of ra3xdh.

The goal of this tool is to be able to read and display S-parameter data (for now, magnitude only). Basically I have ported to CPP the code from [1] and added some features like the ability to open n-port files and have data markers.

The tool is accessible from the Tools menu. It has a single window divided into three panels: one on the right (chart) and two stacked panels on the left (axis settings, file management, trace management and markers).

MainWindow

S-parameter files can be opened by dragging and dropping them onto the S-parameter files area. For 2-port files, the tool automatically displays S21, S11 and S22. It also automatically calculates important metrics for 2-port devices such as K, mu, MAG, etc.

If several s2p files are added on a row, it shows all the S21 traces.

The user can add data markers. Trace data is displayed in a table

Selection_036

This is an screencast showing how it works:

https://drive.google.com/file/d/1tMzdM6z_twqlb8ezXjk8dJaYi-Dm-o-e/view?usp=drive_link

I have tested a number of S-parameter files. I collected a few examples in this [spreasheet](https://docs.google.com/spreadsheets/d/1HVCVMEZUZn-DZSezxQRUszXL5L1tcXybsjiKR4xNaXU/edit?usp=sharing). Please find in [2] the test workspace I used for this.

[1] https://rfdesigntools.pythonanywhere.com/tool/s-parameter-viewer
[2] [SPAR Viewer Testbench_prj.zip](https://github.com/user-attachments/files/16921127/SPAR.Viewer.Testbench_prj.zip)

### CODE REVIEW

**Comment by andresmmera** [comment]
Any guess on how to fix this?

image

**Comment by ra3xdh** [comment]
Thanks for the contribution! I will evaluate the new tool and report the feedback. The most probably I will merge this after preparing v24.3.1 package. Or maybe I will cancel the 24.3.1 release and make 24.4.0 including a new tool instead. 

> Any guess on how to fix this?

The `qtcharts` should be added in `.github/workflows/deploy.yml` according this guide: https://github.com/jurplel/install-qt-action

**Comment by ra3xdh** [comment]
The CI still failing but another error appears:

~~~
No rule to make target '/home/vvk/qucs_s/qucs-s-spar-viewer/qucs-s-spar-viewer.hspar_viewerf', needed by 'qucs-s-spar-viewer/moc_qucs-s-spar-viewer.cpp'.  Stop.
~~~

 I am getting the same error when trying to build a new tool locally. This is not related to CI. I guess some files may be presented locally but missing in commit.

**Comment by andresmmera** [comment]
I see. I'll check that later.

**Comment by andresmmera** [comment]
> I am getting the same error when trying to build a new tool locally. This is not related to CI. I guess some files may be presented locally but missing in commit.

You need to install "libqt5charts5-dev". 

I set up a fresh Lubuntu 24.04 in a VM and followed the instructions you provide in README:

```
sudo apt-get install ngspice build-essential git cmake qtbase5-dev qttools5-dev libqt5svg5-dev flex bison gperf dos2unix
git submodule init
git submodule update
mkdir builddir
cd builddir
cmake ..  -DCMAKE_INSTALL_PREFIX=/your_install_prefix/
make
make install
```
After installing "libqt5charts5-dev" it went fine. 

I'll continue tomorrow with this stuff.

**Comment by ra3xdh** [comment]
> You need to install "libqt5charts5-dev".

I am using Qt6. Bot qt5-chart and qt6-charts development version are installed on my machine. Need further investigations.

**Comment by dsm** [comment]
I tried to include Qtcharts like this `#include <QtCharts/QtCharts>`

and CI compiler give error this line `using namespace QtCharts;` QtCharts is not a name space name

**Comment by ra3xdh** [comment]
> and CI compiler give error this line using namespace QtCharts; QtCharts is not a name space name

See this note: https://doc.qt.io/qt-6/qtcharts-changes-qt6.html

**Comment by ra3xdh** [comment]
@andresmmera Try to apply the following patch. It fixes the Qt6 build. Now I am able to build the tool locally using the Qt6.7.2 on Linux. 

~~~
diff --git a/qucs-s-spar-viewer/qucs-s-spar-viewer.cpp b/qucs-s-spar-viewer/qucs-s-spar-viewer.cpp
index 75b6dacd..79d53c33 100644
--- a/qucs-s-spar-viewer/qucs-s-spar-viewer.cpp
+++ b/qucs-s-spar-viewer/qucs-s-spar-viewer.cpp
@@ -39,7 +39,7 @@
 Qucs_S_SPAR_Viewer::Qucs_S_SPAR_Viewer()
 {
 
-  QWidget *centralWidget = new QWidget(this);  
+  QWidget *centralWidget = new QWidget(this);
   setCentralWidget(centralWidget);
 
   setWindowIcon(QPixmap(":/bitmaps/big.qucs.xpm"));
@@ -560,7 +560,7 @@ void Qucs_S_SPAR_Viewer::addFiles(QStringList fileNames)
           //qDebug() << line;
 
            if (line.isEmpty()) continue;
-           if ((line.at(0).isNumber() == false) && (line.at(0) != "#")) {
+           if ((line.at(0).isNumber() == false) && (line.at(0) != '#')) {
                if (file_data["frequency"].size() == 0){
                    // There's still no data
                    continue;
@@ -572,7 +572,7 @@ void Qucs_S_SPAR_Viewer::addFiles(QStringList fileNames)
 
            }
            // Check for the option line
-           if (line.at(0) == "#"){
+           if (line.at(0) == '#'){
 
                QStringList info = line.split(" ");
                frequency_unit = info.at(1); // Specifies the unit of frequency.
@@ -1443,7 +1443,7 @@ void Qucs_S_SPAR_Viewer::updateTraces()
         QString data_file = trace_name_parts[0];
         QString trace_file = trace_name_parts[1];
 
-        if (trace_file.at(0) == "S"){
+        if (trace_file.at(0) == 'S'){
             trace_file = trace_file + QString("_dB");
         }
         if (trace_file == QString("|%1|").arg(QChar(0x0394))){
@@ -1603,7 +1603,7 @@ void Qucs_S_SPAR_Viewer::checkFreqSettingsLimits(QString filename, double& fmin,
                 disconnect(QCombobox_x_axis_units, SIGNAL(currentIndexChanged(int)), this, SLOT(updatePlot())); // Needed to avoid duplicating the call to the update function
                 disconnect(QSpinBox_x_axis_max, SIGNAL(valueChanged(int)), this, SLOT(updatePlot())); // Needed to avoid duplicating the call to the update function
                 disconnect(QSpinBox_x_axis_min, SIGNAL(valueChanged(int)), this, SLOT(updatePlot())); // Needed to avoid duplicating the call to the update function
-                QCombobox_x_axis_units->setCurrentIndex(index+1);               
+                QCombobox_x_axis_units->setCurrentIndex(index+1);
                 QSpinBox_x_axis_min->setValue(fmin);
                 QSpinBox_x_axis_max->setValue(fmax);
                 connect(QCombobox_x_axis_units, SIGNAL(currentIndexChanged(int)), SLOT(updatePlot()));
@@ -1643,7 +1643,7 @@ void Qucs_S_SPAR_Viewer::checkFreqSettingsLimits(QString filename, double& fmin,
 void Qucs_S_SPAR_Viewer::adjust_y_axis_to_trace(QString filename, QString tracename){
     qreal minX, maxX, minY, maxY;
 
-    if (tracename.at(0) == "S"){
+    if (tracename.at(0) == 'S'){
         tracename = tracename + QString("_dB");
     }
     if (tracename == QString("|%1|").arg(QChar(0x0394))){
diff --git a/qucs-s-spar-viewer/qucs-s-spar-viewer.h b/qucs-s-spar-viewer/qucs-s-spar-viewer.h
index ebfb67f7..1c801bb1 100644
--- a/qucs-s-spar-viewer/qucs-s-spar-viewer.h
+++ b/qucs-s-spar-viewer/qucs-s-spar-viewer.h
@@ -13,7 +13,9 @@
 #include <QtGlobal>
 #include <complex>
 
+#if QT_VERSION < QT_VERSION_CHECK(6,7,0)
 using namespace QtCharts;
+#endif
 
 class QComboBox;
 class QTableWidget;
~~~

**Comment by andresmmera** [comment]
Thanks Vadim.

I'll apply that ASAP, probably this afternoon.

**Comment by dsm** [comment]
I think this line should be this, #if QT_VERSION < QT_VERSION_CHECK(6,0,0)

**Comment by ra3xdh** [comment]
> I think this line should be this, #if QT_VERSION < QT_VERSION_CHECK(6,0,0)

Yes, the QtCharts namespace was deprecated since 6.0.0

**Comment by andresmmera** [comment]
I have updated my Qt setup to v6.7.2. I've applied the patch above. Let's see what happens with the CI.

**Comment by dsm** [comment]
You have to add qt6-charts:p under pacboy in ci for windows

**Comment by ra3xdh** [comment]
I have just checked Qt5.15 and Qt6.2.4 build on Ubuntu-22.04. Both Qt version setup compiles and works as expected. @andresmmera  Please add the `libqt5charts5-dev` dependency in the `.github/workflows/cmake.yml` This will fix the Qt5 CI build.

**Comment by andresmmera** [comment]
Sure. I'll do so this evening

**Review by ra3xdh — APPROVED** [review]

**Comment by andresmmera** [comment]
I've found some warnings in the Qt6 build. I want to fix them before you merge this.

For some reason, I'm not catching them in locally QtCreator.

**Comment by ra3xdh** [comment]
Is it ready for merge now?

**Comment by andresmmera** [comment]
Yes. I think it's ready

**Comment by dsm** [comment]
New tool is missing in macos ci, copy this tool to in qucs.app and run macdeployqt like other tools, there are two macos ci.

**Comment by andresmmera** [comment]
> New tool is missing in macos ci, copy this tool to in qucs.app and run macdeployqt like other tools, there are two macos ci.

Done. Thank you!

**Comment by dsm** [comment]
I'll try to test this tool on MacOS this evening

**Comment by andresmmera** [comment]
@ra3xdh Don't merge this PR yet. I've found that the tool can load the same file twice.

I want to fix this issue before merging. I'll try to fix today.

**Comment by andresmmera** [comment]
I've also added a commit to fix a wrong behaviour concerning the button styles in Windows.

**Comment by dsm** [comment]
I think you can keep as it is, in macos, tools has different icon from qucs-s but that icon has only .icns file has not svg file so we should design a new icon for tools or use qucs-s.svg anywhere. @ra3xdh what do you think about it?

**Comment by ra3xdh** [comment]
>  @ra3xdh what do you think about it?

Let's keep the icons as is.

**Comment by ra3xdh** [comment]
I am merging this. I think the tool is mostly ready for usage. @andresmmera , Please stay connected if some feedback will appear from users after testing the next continuous release.

**Comment by andresmmera** [comment]
Ok, no worries

**Pull request merged**
