### PR TITLE
Add contributing guidelines

### PR DESCRIPTION
**Pull request by wawuwo**
Work in progress #583 

I politely invite anyone interested to discuss and to offer ideas.

In current draft codestyle guidelines are scarce and it may be a lot of work to describe them all, but if every one agrees on using `clang-format` (or some other tool?) I can prepare a config for it instead of describing everything in plain text.

### CODE REVIEW

**Comment by zergud** [comment]
1. for now we have c++11 for qt5 and c++17 for qt6
so "everything up and including C++20" is too fresh )
2. some points need to be reflected:
- new features develop in "current" brunch
- bug fixes for current release in "release/YY.N" which is created immediately after release, and cherypicked to current brunch
- new features and bug fixes must be implemented in separate branches
- branch names should preferably include a ticket number, aka "310-fix-windows-size"

**Comment by wawuwo** [comment]
I've added a fixup commit reflecting your notes. 

PS. I wonder why the build was triggered, #586 should have disabled building workflows on non-C++ files. Maybe because this brunch is based on pre-#586 commit… I'll rebase and force push later to check

**Comment by zergud** [comment]
I think this is good start point
next step is create .clang-format file to control coding statdards 
and evolutionarily reformat all files... in future :)

**Comment by zergud** [comment]
@ra3xdh need you opinion

**Comment by ra3xdh** [comment]
> so "everything up and including C++20" is too fresh )

Yes, we still need to support Ubuntu20.04 which will be EOL in 2025. It may not support C++20 features. 

> @ra3xdh need you opinion

I thinks this PR could be merged. The proposed contribution guide may be accepted.

**Comment by zergud** [comment]
@wawuwo  please remove draft header

**Comment by ra3xdh** [comment]
Merged.

**Pull request merged**
