### PR TITLE
fix path.

### PR DESCRIPTION
**Pull request by dsm**
Hi, I just fixed some path, AppImage first run can't find ngspice. Adding double seperator cause issue. Sometimes windows don't find but I can't find to way to delete settings (first run case)

### CODE REVIEW

**Comment by ra3xdh** [comment]
What happens when `QucsSettings.BinDir` has no separator on the end? Maybe to put the `QDir::separator()` between the `BinDir` and `ngspice.exe`?

**Comment by dsm** [comment]
I think, I use something like that. `QDir(QucsSettings.BinDir).absoluteFilePath("ngspice.exe")`

example:
```
QString BinDir =     QucsDir.canonicalPath();
qDebug() << "Application Directory:" <<BinDir<<'\n'<< QDir(BinDir).absoluteFilePath("ngspice.exe");
```

output:
```
Application Directory: "C:/Users/MuhammetDemir/Documents/untitled/build/bin" 
 "C:/Users/MuhammetDemir/Documents/untitled/build/bin/ngspice.exe"
```

**Comment by ra3xdh** [comment]
> I think, I use something like that. 

Yes, this will be also a solution.

**Comment by dsm** [comment]
I try to change thanks.

**Comment by dsm** [comment]
@ra3xdh I'm done with this PR.

**Comment by ra3xdh** [comment]
Yes, the `QStandardPaths` is a better solution. Merging. Don't forget to test everything in a fresh VM before the release.

**Comment by dsm** [comment]
Yes, I delete settings file and test all AppImage, Windows, and MacOS release but In MacOS it's hard to delete settings because OS is extreme caching and deleting not worked. I completely delete and reboot OS then everything is normal.

**Pull request merged**
