### PR TITLE
Replace Q3PtrList in diagram dialog

### PR DESCRIPTION
**Pull request by wawuwo**
Hi!

This is another piece for #748

### CODE REVIEW

**Comment by dsm** [comment]
Hi, can we use QList instead of std::vector for this refactoring.

**Comment by wawuwo** [comment]
@dsm hi! Is there a specific reason for it? `QList` and `std::vector` both array-based, `Graph` is a private member of diagram dialog and is not passed as argument to any of QT APIs

**Comment by dsm** [comment]
Btw I Quick test QList over std::vector soke compiler error happend, I think QList wants to copy uniquie ptr somewhere I don't but unique ptr doesn't copyable just movable maybe we can use weak_ptr or shared_ptr instead of unique if there isn't spesific desicion.

**Comment by wawuwo** [comment]
I am more inclined to keep the `std::vector` for this one… It works nice and easy in all cases except of removing an element, and here is only one case of removing (plus I just like to stick with standard library facilities when possible). But anyway, thanks for the advice and attention to details

**Comment by ra3xdh** [comment]
Merged. I didn't find issues while testing this.

**Pull request merged**
