### PR TITLE
Add MetaInfo

### PR DESCRIPTION
**Pull request by NN708**
Add AppStream MetaInfo for #51 .

### CODE REVIEW

**Comment by ra3xdh** [comment]
Please move this file to `contrib` subdirectory in the repository root. The purpose of this directory is to hold different stuff mostly related to packaging. https://github.com/ra3xdh/qucs_s/tree/current/contrib

**Comment by ra3xdh** [comment]
Maybe create `contrib/flatpak` subdirectory and put the both MetaInfo and manifest here.

**Comment by NN708** [comment]
> Maybe create `contrib/flatpak` subdirectory and put the both MetaInfo and manifest here.

Since we will have the manifest under [Flathub](https://github.com/flathub/), I don’t think we need to duplicate it. And the MetaInfo is useful for more than just Flatpak.

**Comment by ra3xdh** [comment]
Merged.

**Pull request merged**
