### PR TITLE
Add QucsatorRF stuff

### PR DESCRIPTION
**Pull request by ra3xdh**
This PR implements changes proposed by #370. The following features included:

* Qucsator RF added as Git submodule https://github.com/ra3xdh/qucsator_rf
* Digital simulation scripts updated to use Qucsconv
* `vcd2qucsdat` excluded from build and replaced by `qucsconv_rf`
* Qucs-S main application tries to find QucsatorRF executable on first start

Run the `git submodule init && git submodule update` before compiling Qucs-S.

@zergud , @wawuwo , @iwbnwif You are welcome to test this and post feedback.

### CODE REVIEW

**Comment by ra3xdh** [comment]
MXE build of the Windows execultable doesn't work anymore after adding QucsatorRF stuff. I had success only using MSYS2.

**Comment by zergud** [comment]
good job!
one thing: is there any real benefit of separating repositories?
for me single repo easier to maintain and develop, since the element parameters must be consistent in both part

**Comment by wawuwo** [comment]
I've built it on Debian Bookworm and except a dozen of warnings everything worked seamlessly. Also `gperf` and `dos2unix` must be installed for build to complete, so build instructions should be updated.

I believe that was a piece of work, that's great job :+1:

**Comment by ra3xdh** [comment]
@zergud 
>  is there any real benefit of separating repositories?

In the long perspective the simulation kernel may be packaged separately and used in a CLI mode or even with another GUI. So, I am inclined to keep the `qucsator_rf` in a separate repository and link it with the main project using submodules. Also, it would be hard to preserve commit history when merging two repositories in one. 

> so build instructions should be updated.

Yes, I will update the build instructions.

**Comment by iwbnwif** [comment]
Thank you, it all seems to work well on a pretty standard Ubuntu 22.04.

**Comment by ra3xdh** [comment]
@zergud , @wawuwo , @iwbnwif Thanks for the testing! I will merge this PR. The DEB/RPM package generation scripts on OBS will be updated in order of release preparation.

**Pull request merged**
