### PR TITLE
Prepare for CDL netlist export

### PR DESCRIPTION
**Pull request by ThomasZecha**
Basic introductory refactoring work for code parts affected/used by the new feature CDL netlist export (https://github.com/ra3xdh/qucs_s/discussions/876)
based on https://google.github.io/styleguide/cppguide.html:
 -Prefix class attributes with a_ (much more better readability!)
 -Class member initialization via constructor member initialization list
 -No public class attributes

### CODE REVIEW

**Comment by ra3xdh** [comment]
> Is there a particular reason why old Q3PtrList is used?

The total removing of the Q3PtrList wrapper is planned. See #748 The main concern is "auto delete" feature. Some internal logic may depend on it. It requires to carefully review every occurrence of Q3PtrList. The ideas and contributions are welcome. The same for other remaining Qt3 wrappers from `qt3compat` subdirectory. It the long perspective all qt3support leftover must be removed.

**Comment by ra3xdh** [comment]
> Basic introductory refactoring work for code parts affected/used by the new feature CDL netlist export

The commit name and PR name are a bit misleading. Maybe better *Prepare for CDL netlist export*.

**Comment by ThomasZecha** [comment]
New title _Prepare for CDL netlist export_ is ok for me

**Comment by ThomasZecha** [comment]
"_The main concern is "auto delete" feature._"
I think that can be fully assured by the shared-pointer logic.

**Comment by ra3xdh** [comment]
I have planned merging. I will provide a review or merge in the next week.

**Comment by ThomasZecha** [comment]
Thanks for the info!

**Comment by ra3xdh** [comment]
Please resolve conflict at `externsimdialog.cpp` and rebase if necessary. The conflict has appeared after merging #1057

**Comment by ThomasZecha** [comment]
Rebased and resolved conflict.

**Comment by ra3xdh** [comment]
Merged.

**Pull request merged**
