### PR TITLE
Fix component font size when Qt::HighDpiScaleFactorRoundingPolicy is set

### PR DESCRIPTION
**Pull request by wawuwo**
@zergud, hi!

This is an attempt to fix the bug you described [there](https://github.com/ra3xdh/qucs_s/issues/469#issuecomment-1903477584). Hopefully you still have access to HiDPI hardware you were using when you discovered the bug. Could you please check whether this patch helps or not?

I open PR as a draft in case the patch doesn't fix the issue.

### CODE REVIEW

**Comment by zergud** [comment]
Hi!
I can check this patch in 2 days
if anyone can do it sooner, it would be nice )

**Comment by zergud** [comment]
this patch helps!
blurry font in the menu is another problem )

p.s. why are there parentheses on line 56 and 60 (maybe I don't know something in C++)?

image

**Comment by wawuwo** [comment]
@zergud 
>this patch helps!

This is very good news! I'll mark PR as read for review then.

>why are there parentheses on line 56 and 60 (maybe I don't know something in C++)?

I put those three statements in a dedicated block because they're closely relatated and to restrict the scope of `fontInfo` and `fontSize` because they aren't needed anywhere else. My intention was to enhance readability.

There is also a nice side-effect that block-variables are [destroyed ](https://en.cppreference.com/w/cpp/language/statements#Compound_statements) after leaving the block. So once `fontInfo` and `fontSize` have been used to set up font size, they aren't needed anymore and could be safely destroyed.

I'm not much of an C++ expert and I'm not 100% sure that it's a good thing do so, but at least it looks reasonable to me :)

**Comment by zergud** [comment]
I assumed something like this
but method ViewPainter::init is not  "very complicated", and I think this is premature optimization and affects readability
In any case, until the coding standards are approved, this is just me grumbling ;)

**Pull request merged**
