### PR TITLE
added windows ci continuous release

### PR DESCRIPTION
**Pull request by dsm**
Hi,

this PR add snapshot release for windows

### CODE REVIEW

**Comment by ra3xdh** [comment]
Thanks! The snapshot build seems to work. What is the purpose to include DX shader compiler DLLs in the snapshot package?

**Comment by dsm** [comment]
Because of windeployqt-qt6.exe shows warning to not found them

**Comment by ra3xdh** [comment]
The DXC compiler DLLs seems to be optional dependency. I have tried to remove this from distribution and everything works fine. I have tried both Linux/Wine and physical Windows 11 platforms.  The warning from `windeployqt` may be ignored.

**Comment by ra3xdh** [comment]
Thanks for the contribution! I have merged this.

**Comment by dsm** [comment]
For 2 weeks I have master exams and then I will make improvements.

**Pull request merged**
