### PR TITLE
Graph limits by mouse

### PR DESCRIPTION
**Pull request by iwbnwif**
This is an initial PR for improvements to the diagrams to allow user interaction directly in the schematic. 
This first step makes it possible to 'zoom in' on a diagram by making a selection. In effect, this sets the limits that are already implemented in the diagram dialog.
Currently, only rectangular diagrams are supported.

### CODE REVIEW

**Comment by zergud** [comment]
1. single click on the diagram in "set limits" mode gives "strange" results
2. if no graph falls within the rectangle - "strange" results

I suggest checking whether the graph falls within selection rectangle

**Comment by zergud** [comment]
also, i get error "exp10() undeclared" on my PC
for testing replace to pow(10, x) 
suggest to use pow(10, x)!

**Comment by iwbnwif** [comment]
> also, i get error "exp10() undeclared" on my PC for testing replace to pow(10, x) suggest to use pow(10, x)!

Sorry, yes this is a gcc extension - I will replace with pow(10, x) as you suggest.

**Comment by iwbnwif** [comment]
> 1. single click on the diagram in "set limits" mode gives "strange" results

I have added a check for a minimum size for the selection. Previously, a single click generated a selection rectangle 1x1px so went to max zoom.

> 2. if no graph falls within the rectangle - "strange" results
> I suggest checking whether the graph falls within selection rectangle

Actually, there were already checks for a) starting in a rectangular diagram; and b) finishing in the same diagram as when the dragging started. It is just that the display wasn't refreshed on a failure! It does refresh now, so the strange results have gone, but there is no warning to the user. Hopefully, this is okay?

**Comment by zergud** [comment]
@iwbnwif thank you for contribution

**Comment by zergud** [comment]
I'll add your commit without PR

**Comment by zergud** [comment]
found another bug
rigth axis not scaling ( variable zAxis  %) )
reopen issue, make new PR with right-clicking fix to

**Pull request merged**
