### PR TITLE
Improve graph rendering performance

### PR DESCRIPTION
**Pull request by wawuwo**
Hi! 

A quick and dirty attempt to deal with bad rendering performance of graphs.
It's not the best, but it should do the thing. I can see the actual difference when opening the sample circuit from #984 on my machine.

### CODE REVIEW

**Comment by SmallJoker** [comment]
Thank you for the PR. I tested the [AppImage](https://github.com/ra3xdh/qucs_s/actions/runs/11654355904) a little bit, and so far it does indeed fix the performance issue. No visual issues found.

**Comment by zergud** [comment]
good solution for lines!
remains drawArrowSymbols drawStarSymbols (!!) drawCircleSymbols

**Comment by iwbnwif** [comment]
I am not sure if it is related to this optimisation, but I have a line being drawn to infinity if I zoom in on the chart.

image

[Test1.sch.txt](https://github.com/user-attachments/files/17617489/Test1.sch.txt)

**Comment by ra3xdh** [comment]
@wawuwo , Yes were considering a similar solution with points number decimation. The freezes are gone, but some problem still exist.

* The dashed curves look odd. See the screenshots from old (before #723) and new version. This problem is not related to this fix and may be fixed by a separate PR. 

old:
image

new:
image

* I confirm the problem reported by @iwbnwif Something strange happens when using *Set diagram limits*

@zergud The circles, arrows, and stars count usually should be equal to point number. The typical usecase is a Fourier simulation (arrows) and matching of the few points of experimental data (stars). 

image

**Comment by ra3xdh** [comment]
The problems with dashed curve and *Set limits* are fixed. I will merge this once the CI finishes.

**Comment by ra3xdh** [comment]
Merged.

**Comment by zergud** [comment]
and yet, the behavior when using stars and circles is not correct when there are a large number of points in the dataset

black bold line - circle
red - stars 

image

I think we can find a solution similar to the proposed algorithm for decimation of points
of course in another PR :)

**Comment by ra3xdh** [comment]
Octave package has the same behavior as Qucs-S when using stars line style. Here is the screenshot from Octave. Blue curve is stars 2000 points, redcurve is stars 20 points. So I would keep the stars/circles in Qucs-S as is. 

image

image

**Pull request merged**
