### PR TITLE
Implement native Debian packaging

### PR DESCRIPTION
**Pull request by aol-nnov**
Hi, guys!

I saw you're making some downstreaming efforts in #306 so, I decided to implement native Debian packaging.

Unfortunately, I do not have resources for maintaining the package in the distro (if you wonder 😄 )

Keep up the good work!

Best,
Andrey

### CODE REVIEW

**Comment by aol-nnov** [comment]
@ra3xdh if you willing to propose your software to Debian distro, according to [this FAQ](https://mentors.debian.net/sponsors/rfs-howto/), after merging this PR, you need to send email to submit@bugs.debian.org with the following contents:

```
Package: sponsorship-requests
Severity: normal

I am looking for a sponsor for my package "qucs-s":

 * Package name     : qucs-s
   Version          : 2.1.0-1
   Upstream contact : Vadim Kuznetsov <ra3xdh@gmail.com>
 * URL              : https://github.com/ra3xdh/qucs_s
 * License          : GPL-2.0
 * Vcs              : https://github.com/ra3xdh/qucs_s.git
   Section          : electronics
```

Probably, it worth CC-ing Debian Electronics Team <pkg-electronics-devel@alioth-lists.debian.net>

**Comment by ra3xdh** [comment]
Thanks for the contribution and pointing the procedure for adding package in Debian. I will consider submission of the proposal.

**Comment by ra3xdh** [comment]
I submit the sponsorship request to the Debian mailing list. Let's wait for result.

**Comment by ra3xdh** [comment]
See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1067426

**Pull request merged**
